### ISSUE TITLE
owt.all_cans should have a column specifying the subassembly

### ISSUE THREAD

**Issue by wweijtje** [OWI-Lab/owimetadatabase-preprocessor#10]
the all_cans command should provide a column that specifies the sub assembly (i.e. Tower, MP, TP, ... ) . While this can currently be inferred from the can's name, that is just because we keep that convention there is no obligation to adhere to it. E.g. one can perfectly have an element ('bbc01_001') 

I think when we are going to add tubular sections linked e.g. to the grout or other, that this will become very helpful.

**Comment by wweijtje** [comment]
This also applies for `owt.all_distributed_mass`  and `owt.all_lumped_mass`

**Comment by arsmlnkv** [comment]
While this was added, another issue is that we use titles now to determine the sub assembly type from "raw" dataframes for processing. Because of that I thought it was a standard practice, i.e. fixed format for building blocks names...
