### ISSUE TITLE
Dependency to scipy motivated?

### ISSUE THREAD

**Issue by wweijtje** [OWI-Lab/owimetadatabase-preprocessor#14]
I always try to avoid dependencies to scipy when there is a valid alternative. I notice often scipy is imported for just a single function where often an equivalent (most often within numpy) exists. 

The reason is that scipy comes in at a whopping 45MB. 

![image](https://github.com/OWI-Lab/owimetadatabase-preprocessor/assets/85878088/1200bdc8-9b89-464c-8774-10a2b767ecec)

Of course there are definitely functions that require scipy and if it is not just one, then it is ok. But is a dependency I always hunt down :-)

**Comment by arsmlnkv** [comment]
It is required for the groundhog package which is required for soil stuff. I guess in the near future, when we split the package, it  can be avoided for the basic functionality package like geometry/locations.

**Comment by arsmlnkv** [comment]
I removed this dependency from the latest stable version (without soil functionality). When it will be realised in full, I will return it.
