### ISSUE TITLE
Impossible to update the layout of `plot_turbines`

### ISSUE THREAD

**Issue by wweijtje** [OWI-Lab/owimetadatabase-preprocessor#15]
If a user is not satisfied with the layout of the `plot_turbines` command it is no longer possible to update its properties.

It would be helpful if `plot_turbines` returns the plotly Figure object so you can run `fig.update_layout(...)` when needed.

This also applies for
`locations_api.plot_assetlocations(projectsite=projectsite)`

For illustration, in my usecase it really is too small

![image](https://github.com/OWI-Lab/owimetadatabase-preprocessor/assets/85878088/01767ac4-2c75-496d-b094-b549904a124b)

**Comment by arsmlnkv** [comment]
Should the functionality of plot_turbines() be moved/copied to get_owt_processor object?

**Comment by arsmlnkv** [comment]
Fixed in commit d373c6856b66f2c9c2edee4e28f69dc874343062 and is in the new release [v0.6.1.](https://github.com/OWI-Lab/owimetadatabase-preprocessor/releases/tag/v0.6.1)
