### ISSUE TITLE
Wrong labels

### ISSUE THREAD

**Issue by csasj** [OWI-Lab/owimetadatabase-preprocessor#18]
Wrong labels in the exported dataframe (see attachment)  
- ```from``` and ```to``` seem to be inverse. 

![image](https://github.com/OWI-Lab/owimetadatabase-preprocessor/assets/69809839/ad2978a1-fa89-45f1-bc99-b6f862a8fb22)

Besides, I've a request to facilitate the modeling later. Please, to refer to elevation or altitude, use the keyword ```Elevation``` instead of ```Height```.  The keyword ```Height``` remains to refer to the actual length of the tubular sections.

**Comment by arsmlnkv** [comment]
The naming was just changed to 'Elevation from/to' in the latest release according to the request. But the column order in the example above is wrong in this spreadsheet as pointed out by @csasj. The package was giving the correct columns-data combinations so it might be an issue during the manual/custom moving of dataframes into csv, excel. @wweijtje

**Comment by arsmlnkv** [comment]
The issue with the spreadsheet was not caused by the package.
