### ISSUE TITLE
Tower mass calculation includes RNA!

### ISSUE THREAD

**Issue by csasj** [OWI-Lab/owimetadatabase-preprocessor#21]
Dataframe of the general geometry data from each turbine is stored as dataframe in` all_turbines`. The displayed tower mass can not be correct. It seems that the RNA mass is also included, which should not. 

![image](https://github.com/OWI-Lab/owimetadatabase-preprocessor/assets/69809839/64ecdf67-6ab3-4c56-889b-070c75872dfe)

**Comment by arsmlnkv** [comment]
It was excluded into a separate column as requested.
