### ISSUE TITLE
owt.all_turbines return None when owt.process_structure() is not ran

### ISSUE THREAD

**Issue by wweijtje** [OWI-Lab/owimetadatabase-preprocessor#9]
This is covered in the example notebook, but it was a bit weird to me that there was no warning or anything when I tried to run it without first running 'owt.process_structure()'

I understand that you want to avoid the timeconsuming step of the process_structures, but I would have expected a warning stating that process_structure had to be ran first

**Comment by arsmlnkv** [comment]
It is a valid point. I mainly followed the same logic as in the legacy code. Need to think about the best way to address that. I will try to maybe give some sort of warning for now indeed, but I will also keep this issue open until we agree on the best way.
